server:
  port: 8084

spring:
  application:
    name: LMS-API-GATEWAY  
  cloud:
    gateway:
      routes:
      - id: lb://UserCandidate
        uri:
          http://localhost:8081/
        predicates:
        - Path=/usercandidate/** 
      - id: lb://UserAdmin
        uri:
          http://localhost:8082/
        predicates:
        - Path=/useradmin/**     
    

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8762/eureka
    